### ISSUE TITLE
String index out of range error in Knitpy.render with output='all'

### ISSUE THREAD

**Issue by thatcher** [JanSchulz/knitpy#6] opened 2015-04-13 20:27 UTC
Sting index out of range error can be reproduced as follow:

```
>>> from knitpy.knitpy import Knitpy
>>> report = Knitpy()
>>> report.render('./knitpy_overview.pymd', output='all')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "build\bdist.win-amd64\egg\knitpy\knitpy.py", line 716, in render
  File "build\bdist.win-amd64\egg\knitpy\documents.py", line 175, in content
  File "build\bdist.win-amd64\egg\knitpy\documents.py", line 192, in flush
  File "build\bdist.win-amd64\egg\knitpy\documents.py", line 185, in _ensure_newline
IndexError: string index out of range
```

I was able to work around this by changing:
```python
    def _ensure_newline(self):
        # don't add a newline before any output
        if not self._output:
            return
        if self._output[-1][-1] != "\n":
            self._output.append("\n")
```

to:

```python
    def _ensure_newline(self):
        # don't add a newline before any output
        if not self._output:
            return
        if self._output[-1] != "\n":
            self._output.append("\n")
```

Which seems intuitively to be what was intended.  I'll submit a pull request if this makes sense.  If its easier you can just patch.

**Comment by JanSchulz** [comment] 2015-04-13 20:42
Thanks for the bugreport, I could reproduce it here but I've currently no clue what the problem is.

The patch above is unfortunately not right, as `_output` is a list of strings, so `self._output[-1][-1]` should be the last letter of the last output. In this case it seems that an empty string was added. I will have to prevent adding empty strings and some place in the code..

**Comment by JanSchulz** [comment] 2015-04-13 21:25
Ok, found a fix, but I currently have failing unittests due to other commits in the branch :-/. I will rebase on top of current head and push a fix only commit tomorrow...

**Comment by JanSchulz** [comment] 2015-04-13 21:33
merged in #10

**Comment by JanSchulz** [comment] 2015-04-13 21:34
I will leave this open to put in another testcase to the 'compile all' case.

**Closed** 2015-04-13 21:36 UTC

**Comment by thatcher** [comment] 2015-04-14 13:28
Awesome, thanks!
